const FORMAT = 'three-neural-appearance';
const VERSION = 6;
const LATENT_CHANNELS = 8;
const LATENT_TEXTURES = 2;
const CHANNELS_PER_TEXTURE = 4;
const DECODER_INPUT_SIZE = 20;
const IBL_INPUT_SIZE = 14;
const IBL_OUTPUT_SIZE = 4;
const INDIRECT_INPUT_SIZE = LATENT_CHANNELS + 3 + 3;
const INDIRECT_OUTPUT_SIZE = 3;
const IBL_TARGET_SIZE = 17;
const ROTATION_OUTPUT_SIZE = 12;
const DEFAULT_WRAP = 'repeat';

export {
	FORMAT,
	VERSION,
	LATENT_CHANNELS,
	LATENT_TEXTURES,
	CHANNELS_PER_TEXTURE,
	DECODER_INPUT_SIZE,
	IBL_INPUT_SIZE,
	IBL_OUTPUT_SIZE,
	INDIRECT_INPUT_SIZE,
	INDIRECT_OUTPUT_SIZE,
	IBL_TARGET_SIZE,
	ROTATION_OUTPUT_SIZE,
	DEFAULT_WRAP
};
