const FORMAT = 'three-neural-appearance';
const VERSION = 2;
const LATENT_CHANNELS = 8;
const LATENT_TEXTURES = 2;
const CHANNELS_PER_TEXTURE = 4;
const DECODER_INPUT_SIZE = 20;
const ROTATION_OUTPUT_SIZE = 12;
const DEFAULT_WRAP = 'repeat';

export {
	FORMAT,
	VERSION,
	LATENT_CHANNELS,
	LATENT_TEXTURES,
	CHANNELS_PER_TEXTURE,
	DECODER_INPUT_SIZE,
	ROTATION_OUTPUT_SIZE,
	DEFAULT_WRAP
};
